name: Build Sibernetic

on:
  push:
    branches: [ master, dev*, ow* ]
  pull_request:
    branches: [ master, dev, ow* ]

jobs:

  build:

    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ ubuntu-latest ]

    steps:
    - name: Set git to use LF
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf
        
    - uses: actions/checkout@v2

    - name: Set up Python  ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version:  ${{ matrix.python-version }}

    - name: Install Intel OpenCL libraries needed for Sibernetic
      run: |

        # Based on: https://github.com/openworm/OpenWorm/blob/master/Dockerfile
        lscpu
        cat /proc/cpuinfo
        arch
        uname --processor
        uname --machine
        mkdir intel-opencl-tmp
        cd intel-opencl-tmp
        mkdir intel-opencl
        wget https://github.com/openworm/OpenWorm/raw/dev_inte/SRB5.0_linux64.zip
        unzip SRB5.0_linux64.zip
        tar -C intel-opencl -Jxf intel-opencl-r5.0-63503.x86_64.tar.xz
        tar -C intel-opencl -Jxf intel-opencl-devel-r5.0-63503.x86_64.tar.xz
        tar -C intel-opencl -Jxf intel-opencl-cpu-r5.0-63503.x86_64.tar.xz
        sudo cp -R intel-opencl/* /
        sudo ldconfig
        cd ..
        sudo rm -r intel-opencl-tmp

        sudo cp -R /opt/intel/opencl/include/CL /usr/include/
        sudo apt install -y ocl-icd-opencl-dev vim 


        # # download the key to system keyring
        # wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB | gpg --dearmor | sudo tee /usr/share/keyrings/oneapi-archive-keyring.gpg > /dev/null

        # # add signed entry to apt sources and configure the APT client to use Intel repository:
        # echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
        # sudo apt-get update
        # sudo apt-get install -y intel-basekit
        # sudo apt-get install -y intel-oneapi-runtime-opencl

        wget https://master.dl.sourceforge.net/project/nicehashsgminerv5viptools/APP%20SDK%20A%20Complete%20Development%20Platform/AMD%20APP%20SDK%203.0%20for%2064-bit%20Linux/AMD-APP-SDKInstaller-v3.0.130.136-GA-linux64.tar.bz2
        tar -xf AMD-APP-SDKInstaller-v3.0.130.136-GA-linux64.tar.bz2
        # yes Y 2>/dev/null | sudo ./AMD-APP-SDK-v3.0.130.136-GA-linux64.sh
        sudo ./AMD-APP-SDK-v3.0.130.136-GA-linux64.sh
        # sudo apt install -y pocl-opencl-icd
        # ls /usr/include
        # dpkg -L intel-basekit
        # dpkg -L intel-oneapi-runtime-opencl
        echo "ls /opt/intel"
        ls /opt/intel
        echo "ls /opt/intel/opencl"
        ls /opt/intel/opencl
        echo "ls /opt/intel/oneapi"
        ls /opt/intel/oneapi

    - name: Build Sibernetic
      run: |

        sudo apt install -y python3-dev freeglut3-dev libglu1-mesa-dev
        #sudo apt install -y  --allow-downgrades libc-bin=2.27-3ubuntu1.5 # Fails with 2.27-3ubuntu1.6 for some reason...
        python -V
        ls -alt /usr/bin/python*
        ls -alt
        make clean
        make

    - name: Run quick Sibernetic test
      run: |
        ldd ./Release/Sibernetic

        ./Release/Sibernetic -no_g timelimit=0.001

    - name: Final version info
      run: |

        python -V
        pip list
