name: Build Sibernetic

on:
  push:
    branches: [ master, dev*, ow* ]
  pull_request:
    branches: [ master, dev, ow* ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Intel OpenCL libraries needed for Sibernetic
      run: |

        mkdir intel-opencl-tmp
        cd intel-opencl-tmp
        mkdir intel-opencl
        wget https://github.com/openworm/OpenWorm/raw/dev_inte/SRB5.0_linux64.zip
        unzip SRB5.0_linux64.zip
        tar -C intel-opencl -Jxf intel-opencl-r5.0-63503.x86_64.tar.xz
        tar -C intel-opencl -Jxf intel-opencl-devel-r5.0-63503.x86_64.tar.xz
        tar -C intel-opencl -Jxf intel-opencl-cpu-r5.0-63503.x86_64.tar.xz
        sudo cp -R intel-opencl/* /
        sudo ldconfig
        cd ..
        sudo rm -r intel-opencl-tmp
